[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction'
]

[phases.build]
cmds = [
    'mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views',
    'chmod -R 775 storage bootstrap/cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'